# Model arguments
model_name_or_path: /PATH/TO/Qwen2.5-VL-7B-Instruct
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: JefferyZhan/Vision-R1-Data
dataset_configs:
- all
preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: "no"
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

learning_rate: 2.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 3072
max_pixels: 401408 
max_steps: -1
num_train_epochs: 1
output_dir: checkpoints/Qwen2.5-VL-7B-Instruct-sft
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- tensorboard
save_strategy: "no"
seed: 42
warmup_ratio: 0.1